errors are now shown in stdout and in logfile

diff --git a/restic-backup b/restic-backup
--- a/restic-backup
+++ b/restic-backup
@@ -99,16 +99,43 @@ if [ "$2" == "" ]; then
 fi
 
 # Do the job
+dobackup()
+{
+    $prog backup $quiet $verbose --tag $1 --files-from $include --exclude-file $exclude --exclude $RESTIC_PASSWORD_FILE
+}
+
+docheck()
+{
+    $prog check $quiet $verbose
+}
+
+
 log "$0: backup (restic) of $name to $RESTIC_REPOSITORY started."
 
 # Backup
 log "   Backing up to $RESTIC_REPOSITORY ..."
-$prog backup $quiet $verbose --tag $2 --files-from $include --exclude-file $exclude --exclude $RESTIC_PASSWORD_FILE 
 
-#Check
+# This tricky thing captures stderr of dobackup in $err and maintains exit code in $? for evaluation
+{ err="$( { dobackup $2; } 2>&1 1>&3 3>&- )"; } 3>&1
+
+if [ $? -ne 0 ]; then
+    echo $err 1>&2
+    log "   $err" 
+    log "$0: backup (restic) of $name to $RESTIC_REPOSITORY failed."
+    exit 1
+fi
+
+
+# Check
 if [ "$check" != "no" ]; then
     log "   Checking $RESTIC_REPOSITORY ..."
-    $prog check $quiet $verbose
+    { err="$( { docheck; } 2>&1 1>&3 3>&- )"; } 3>&1
+    if [ $? -ne 0 ]; then
+	echo $err
+	log "   $err" 
+	log "$0: backup (restic) of $name to $RESTIC_REPOSITORY failed."
+	exit 1
+    fi
 fi
 
 log "$0: backup (restic) of $name to $RESTIC_REPOSITORY finished."
diff --git a/restic-check b/restic-check
--- a/restic-check
+++ b/restic-check
@@ -77,7 +77,13 @@ log "$0: check (restic) of $RESTIC_REPOSITORY started."
 
 log "   Checking $RESTIC_REPOSITORY ..."
 
-$prog check $quiet $verbose
+{ err="$( { $prog check $quiet $verbose; } 2>&1 1>&3 3<&- )"; } 3>&1
+if [ $? -ne 0 ]; then
+    echo $err
+    log "   $err"
+    log "$0: check (restic) of $RESTIC_REPOSITORY failed."
+    exit 1
+fi
 
 log "$0: check (restic) of $RESTIC_REPOSITORY finished."
 
diff --git a/restic-clone b/restic-clone
--- a/restic-clone
+++ b/restic-clone
@@ -44,7 +44,15 @@ destination=onedrive:backup/$1
 log "$0: cloning (rclone) of $source to $destination started."
 
 log "   Sync (rclone) $source with $destination ..."
-rclone sync -P $quiet $source $destination
+
+{err="$( { rclone sync -P $quiet $source $destination; } 2>&1 1>&3 3>&- )"; } 3>&1
+if [ $? -ne 0]; then
+    echo $err
+    log "   $err"
+    log "$0: cloning (rclone) of $source to $destinatin failed."
+    exit 1
+fi
+
 
 log "$0: cloning (rclone) of $source to $destionation finished."
 exit 0
diff --git a/restic-prune b/restic-prune
--- a/restic-prune
+++ b/restic-prune
@@ -91,6 +91,27 @@ case "$1" in
 	;;
 esac
 
+doprune()
+{
+    { err="$( { prune $1; } 2>&1 1>&3 3>&- )"; } 3>&1
+    if [ $? -ne 0 ]; then
+	echo $err 1>&2
+	log "   $err"
+	log "$0: prune (restic) of $1 failed."
+	exit 1
+    fi
+}
+
+docheck()
+{
+    { err="$( { check $1 $quiet $verbose; } 2>&1 1>&3 3>&- )"; } 3>&1
+    if [ $? -ne 0 ]; then
+	echo $err 1>&2
+	log "   $err"
+	log "$0: check (restic of $1 failed."
+    fi
+}
+
 log "$0: prune (restic) of $1 started."
 
 # prune:
@@ -99,16 +120,18 @@ log "$0: prune (restic) of $1 started."
 # keep 4 weekly snapshots
 case "$1" in
     "lan")
-	prune $repo_lan
-	check $repo_lan
+	doprune $repo_lan
+	if [ "$check" != "no" ]; then docheck $repo_lan; fi
 	;;
     "onedrive")
-	prune $repo_onedrive
-	check $repo_onedrive
+	doprune $repo_onedrive
+	docheck $repo_onedrive
 	;;
     "all")
-	prune $repo_lan; check $repo_lan; \
-        prune $repo_onedrive; check $repo_onedrive
+	doprune $repo_lan
+	docheck $repo_lan 
+        doprune $repo_onedrive
+	docheck $repo_onedrive
 	;;
 esac
 
